### ISSUE TITLE
About config page.

### ISSUE THREAD

**Issue by gchodancar19** [Jforjo/CSD#1]
I have got issues in my login page and the errors are showing on config in most of the lines.

**Comment by Jforjo** [comment]
I believe this to be sorted out within lesson, or to be bought up with the lecturer, so I might advise closing the issue request. Comment again if not though.
Also, for future reference, you should provide much more information about the issue you are experiencing, so we can further help you. Such information could include a screenshot of the error you are getting, along with your code if it hasn't been committed to GitHub, a step-by-step guide as to how you came across this error, and what the intended outcome should be (if not obvious).
