### ISSUE TITLE
CN Stats Page Help Wanted Loading PHP Data into JavaScript Graph

### ISSUE THREAD

**Issue by chrisn02** [Jforjo/CSD#10]
**Description**
I am currently working on loading the test data into the stats page and am currently unsure how to go about loading the data into the graph and nothing I tried has worked. The graph currently displays placeholder data, any help would be appreciated. 

**To Reproduce**
1. Log in as a student that has completed tests
2. Go to the stats page

**Expected Behaviour**
The graph should load the user's past test scores

**Screenshots**
![image](https://github.com/Jforjo/CSD/assets/59711723/a1bdae04-bcda-40dd-b4e1-096de7e600ed) - How the graph currently looks
![image](https://github.com/Jforjo/CSD/assets/59711723/d6bd933a-9a35-4e59-821c-131fc5f49f52) - JS code for loading test names and percentages

**Code Location**
Branch: https://github.com/Jforjo/CSD/tree/CN-UserStatsPage-LoadTestData
Commit: f634e19
Files: user-stats.php & graph.js

**Additional information**
Date & Time of issue: 11/03/2024 09:29

**Comment by Jforjo** [comment]
This could be achieved by putting the Chart inside a function called something like "DisplayChart" that takes an array of integers as a parameter.
Then use JavaScripts `fetch` function to called a PHP file that returns the student's results. Format it, then pass it to the function "DisplayChart".

**Comment by Jforjo** [comment]
Here's the SQL procedure you call, how to call it and what it returns:
![Screenshot showing how to call a SQL procedure and the data it returns](https://github.com/Jforjo/CSD/assets/58900155/829fa0c2-1bc2-4dba-967c-1853f59a2288)

**Comment by chrisn02** [comment]
Sorted. Thanks for your help!
