### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by gchodancar19** [Jforjo/CSD#18]
![image](https://github.com/Jforjo/CSD/assets/132353162/326e67b9-1fcd-4fa3-9827-41f76fd12ba0)

Whenever I try to login this is what it gives me.

**Comment by chrisn02** [comment]
Strange, It works fine for me. What branch are you trying it on? I just tested it on both GC-login-page and GC-Signup-page and it works

**Comment by Jforjo** [comment]
Yeah, please state the branch so I can see your code implementation.
