### ISSUE TITLE
Signup page

### ISSUE THREAD

**Issue by gchodancar19** [Jforjo/CSD#19]
![image](https://github.com/Jforjo/CSD/assets/132353162/bffda8be-5850-4cea-92a1-12e5edf9b10d)
This what it gives me whenever I try to signup.

**Comment by Jforjo** [comment]
Say what branch it is on, or screenshot your code.

**Comment by gchodancar19** [comment]
GC Signup page

**Comment by Jforjo** [comment]
This error is because your inputs on `signup.php` are named 'firstName' and 'lastName' and in your `createuser.php` you are trying to access 'firstname' and 'lastname'. The difference is the capital 'n'.

**Comment by gchodancar19** [comment]
Yeah did that and it works now.
