### ISSUE TITLE
My createuser.php page

### ISSUE THREAD

**Issue by gchodancar19** [Jforjo/CSD#20]
<?php
require_once('php/connection.php');
function CreateUser($firstname,$lastname,$email, $password) {
    $sql = "CALL CreateUser(:ID,:firstname,:lastname,:email,:password);";
    $conn = newConn();
    $stmt = $conn->prepare($sql);
    
    $stmt->bindValue(":ID",bin2hex(random_bytes(16)), PDO::PARAM_STR);
    $stmt->bindValue(":firstname", $firstname, PDO::PARAM_STR);
    $stmt->bindValue(":lastname", $lastname, PDO::PARAM_STR);
    $stmt->bindValue(":email", $email, PDO::PARAM_STR);
    $stmt->bindValue(":password", password_hash($password,PASSWORD_DEFAULT), PDO::PARAM_STR);
    $success=$stmt->execute();
   
    $conn = null;
    
    
   return$success;
}

$data = CreateUser($_POST["firstname"],$_POST["lastname"],$_POST['email'], $_POST['password']);

if ($data === false) {
    header('Location: signup.php?e=5');
} else {
  
    header('Location: login.php');
}

?>

    This is the createuser.php page code can anyone have a look and suggest any ideas if I need to make any changes because my signup page causes error due to that.

**Comment by Jforjo** [comment]
Can you screenshot the code in your file or just state what branch it is on, since the code you pasted here is unformatted and therefore hard to read

**Comment by Jforjo** [comment]
However, if this is in relation to your previous issue then you need to change `name="firstName"` to `name="firstname"` in your signup page, and do the same for the lastname.

**Comment by gchodancar19** [comment]
![image](https://github.com/Jforjo/CSD/assets/132353162/cc178020-0586-4ddb-a625-0c1d9b899f90)

**Comment by Jforjo** [comment]
There's nothing wrong with that page, you should edit your signup page instead.

**Comment by gchodancar19** [comment]
Alright I will try editing my signup page.
