### ISSUE TITLE
CN get correct answer for each question

### ISSUE THREAD

**Issue by chrisn02** [Jforjo/CSD#24]
**Description**
I am currently working on the testing page and there is an error to do with getting the correct answer for each question. I am shown the error message "Warning: Undefined array key "correctAnswer" in C:\xampp2024\htdocs\CSD\pages\student\testing-page.php on line 80" despite being defined and being called from the "GetQuizSet" procedure.

**To Reproduce**
1. Log in as a student that has a quiz to complete
2. Start the test
3. The error message that was shown above will be displayed

**Expected Behaviour**
The correctAnswer should be correctly retrieved and stored for each question

**Screenshots**
![image](https://github.com/Jforjo/CSD/assets/59711723/b6c99401-57de-43be-9ad9-b19b1893c6bc)

**Code Location**
Branch: https://github.com/Jforjo/CSD/tree/CN-TestingPage-LoadTestData
Commit: cfd8f55
File: pages/student/testing-page.php (Line with bug is currently commented out in latest commit)

**Additional Information**
Date & Time of issue: 21/03/2024 19:30

**Comment by chrisn02** [comment]
Have now fixed this by replacing the GetQuizSet procedure with GetAllQuestions

**Comment by Jforjo** [comment]
Yeah, the correct answer should not used in the test section, as the user could simply 'inspect element' and know what the correct answer is. This is why it wouldn't work.
