### ISSUE TITLE
Signup page error

### ISSUE THREAD

**Issue by gchodancar19** [Jforjo/CSD#30]
![image](https://github.com/Jforjo/CSD/assets/132353162/15e68556-4aca-4196-a416-ec17f7fe9f0a)
I tried different email address and it gives the same.

**Comment by Jforjo** [comment]
Don't create a new issue, you should've commented this on your previous issue.
Also, show the code for it.

**Comment by chrisn02** [comment]
Are you getting the same error message as the previous issue?

**Comment by gchodancar19** [comment]
![image](https://github.com/Jforjo/CSD/assets/132353162/c876f126-829e-4b3f-b822-560cab0f4535)
This is the code.

**Comment by Jforjo** [comment]
The code of your create user page, not the signup form.

**Comment by chrisn02** [comment]
Send the code for createuser.php as well

**Comment by gchodancar19** [comment]
Yeah the same issue

**Comment by Jforjo** [comment]
Besides, the text inside the label shouldn't be "firstName", it should be Firstname. Same for lastname.

**Comment by gchodancar19** [comment]
![image](https://github.com/Jforjo/CSD/assets/132353162/b11f818e-372c-4571-bcff-533aecbb7feb)

**Comment by Jforjo** [comment]
Nothing seems wrong with your code and the users are getting created in the database, so I'm not sure why you're getting the error.
![image](https://github.com/Jforjo/CSD/assets/58900155/b52f41c6-6a87-4030-a46d-8ef924147de9)

**Comment by chrisn02** [comment]
Yeah, it seems to work now, so you can commit the code if you haven't already

**Comment by Jforjo** [comment]
You should also change `type="firstName"` to `type="test"`, and the same for the lastname.

**Comment by Jforjo** [comment]
Solved here: https://github.com/Jforjo/CSD/issues/32
