### ISSUE TITLE
CN Test Selection Page Student Create Own Quiz

### ISSUE THREAD

**Issue by chrisn02** [Jforjo/CSD#31]
**Description**
I'm working on the functionality that allows students to create their own quizzes as part of the change request, but am stuck on how I should go about it. The way I currently have is the user selects the subject they would like to create their quiz on and it would choose random questions that are linked to the subject, but I don't think the database is currently set up to do that. Unless theirs a different way to allow users to create their own quizzes

**Expected Behaviour**
The user clicks the create quiz button and a form will appear asking the user to select the subject and amount of questions

**Screenshots**
![image](https://github.com/Jforjo/CSD/assets/59711723/f0e2efcc-ffff-4b48-a002-2b53a0d72c00) The current form that appears after the button is clicked

**Code Location**
Branch: https://github.com/Jforjo/CSD/tree/CN-TestSelectionPage-StudentCreateQuizzes 
Commit: [e7565c9](https://github.com/Jforjo/CSD/commit/e7565c921366fa7fa8df80f5dc6387d2219bed3a)
File: pages/student/index.php

**Additional Information**
Date & Time of Issue: 25/03/2024 14:41

**Comment by Jforjo** [comment]
I believe questions are linked to a quiz, not a subject.

**Comment by chrisn02** [comment]
They are, but in order to allow students to create their own quiz, they need to select a subject and it will assign random questions that are linked to the subject, so I feel having a way to do this might be necessary. For example, if the user selects Maths as the subject, and chooses 10 questions, then it should get 10 random maths questions and assign them to the newly created quiz

**Comment by Jforjo** [comment]
No, questions are linked with a quiz, subjects are also linked with a quiz, but questions are not linked with subjects.

**Comment by chrisn02** [comment]
Ok, how would I go about allowing students to create their own quiz then. Because I asked Jack about it the other day and he said to do it how the Personal Revision feature is done on jTest

**Comment by Jforjo** [comment]
I've just added a 'subject' field to the question table. Tell me if there are any procedures that you want to add it to.

**Comment by Jforjo** [comment]
I've added a procedure called "GetQuizSetFromSubject" that takes a subject ID and a limit value, which then returns the questions IDs along with the question and all the possible answers.

**Comment by chrisn02** [comment]
Ok thanks. I guess a procedure that could be added would be to get the subject that the user chose and assign the questions linked to the subject randomly to the quiz that has just been created and then assign that to the currently logged in student, based off how many questions they chose

**Comment by chrisn02** [comment]
The student is now able to create their own quiz by selecting a subject and number of questions.
