### ISSUE TITLE
Input sanitisation

### ISSUE THREAD

**Issue by gchodancar19** [Jforjo/CSD#32]
![image](https://github.com/Jforjo/CSD/assets/132353162/839290c7-a539-4b8e-afb4-acad9e229dab)
![image](https://github.com/Jforjo/CSD/assets/132353162/115ea01a-5b6b-4aa7-958e-3834241f674d)

Currently I am working on input sanitisation code and this is what it gives me after coding so I don't know whether I need to create in on a new file or auth.php page.

**Comment by gchodancar19** [comment]
The first is the error message which I am getting and below is the code.

**Comment by Jforjo** [comment]
You can use `$newdata = htmlspecialchars($data)` for most of the inputs.
For emails you should use `$newdata = filter_var($data, FILTER_VALIDATE_EMAIL)`.
And for passwords you need to follow the password policy, but I'll give you some of the regex formulas to use:
* at least 1 lowercase letter: "/[a-z]/"
* at least 1 uppercase letter: "/[A-Z]/"
* at least 1 number: "/[0-9]/"
* at least 1 special character: "/[\'^£$%&*()}{@#~?!<>,|=_+¬-]/"

**Comment by gchodancar19** [comment]
Do I have to create code for every single data like firstname and lastname.

**Comment by Jforjo** [comment]
Yes

**Comment by Jforjo** [comment]
For example, here's just some of the checks that I have in place when editing a student:
![image](https://github.com/Jforjo/CSD/assets/58900155/1488eced-92bc-41de-94e1-0c2267ee0f23)

**Comment by gchodancar19** [comment]
Do I have to use if statement.

**Comment by Jforjo** [comment]
Of course.
You need an if statement to check if they have valid data, and if they don't then you need to throw an error and prevent them from going forward.

**Comment by Jforjo** [comment]
You can have a look at https://github.com/Jforjo/CSD/blob/a5eae1a302b08c7572c6cfa382d2bd6634184483/php/editstudent.php for a working example.

**Comment by gchodancar19** [comment]
![image](https://github.com/Jforjo/CSD/assets/132353162/13a8962d-3c55-4af3-b119-9cb48bb4215e)
Can you all please have a look at my auth.php page as I had followed the example provided above.

**Comment by Jforjo** [comment]
Considering how you haven't created a system in JavaScript to handle those responses, you should probably just have something like:
```php
if (!isset($_POST['email']) {
    header("Location: login.php?e=1");
    exit;
}
if (!filter_var($_POST['email'], FILTER_VALIDATE_EMAIL) {
    header("Location: login.php?e=2");
    exit;
}
```
This is just for the email though, and since this is the login form you only need to check the email and password.
You should only check the firstname, lastname etc on the createuser.php, in which case would contain something like this:
```php
if (!isset($_POST['firstname']) {
    header("Location: login.php?e=3");
    exit;
}
if (strlen($_POST['firstname'] > 32) {
    header("Location: login.php?e=4");
    exit;
}
```

**Comment by gchodancar19** [comment]
![image](https://github.com/Jforjo/CSD/assets/132353162/c481ab2d-0462-4d4e-992e-fff606225b93)
![image](https://github.com/Jforjo/CSD/assets/132353162/970db77e-fcfb-486e-b560-db5f3168e349)
I did tried and still it's taking me back to login back.

**Comment by Jforjo** [comment]
There is no filter var for the password, you have to do each of them manually, for example:
```php
if (isset($_POST['password'])) {
    header("Location: login.php?e=1");
    exit;
}
$password = $_POST['password'];
// Checks the lenth of the `password` string
if (strlen($password) < 8) {
    header("Location: login.php?e=1");
    exit;
}
// Checks if the 'password' contains at least 1 lowercase letter
if (preg_match('/[a-z]/', $password) == 0) {
    header("Location: login.php?e=1");
    exit;
}
// Checks if the 'password' contains at least 1 uppercase letter
if (preg_match('/[A-Z]/', $password) == 0) {
    header("Location: login.php?e=1");
    exit;
}
// Checks if the 'password' contains at least 1 number
if (preg_match('/[0-9]/', $password) == 0) {
    header("Location: login.php?e=1");
    exit;
}
// Checks if the 'password' contains at least 1 special character
if (preg_match('/[\'^£$%&*()}{@#~?!<>,|=_+¬-]/', $password) == 0) {
    header("Location: login.php?e=1");
    exit;
}
```
Of course you'll need to change each of the "?e=" so they're al different.

**Comment by gchodancar19** [comment]
Alright I will try that thank you.

**Comment by gchodancar19** [comment]
After creating input sanitisation my login and signup page is not working now.

**Comment by Jforjo** [comment]
You'll need to screenshot the code.

**Comment by gchodancar19** [comment]
![image](https://github.com/Jforjo/CSD/assets/132353162/94805997-77a5-4a19-b9e3-4b56cb4f6a56)
![image](https://github.com/Jforjo/CSD/assets/132353162/7ec38ec6-2a0d-4652-aa3c-ec57d3f21b5b)

**Comment by Jforjo** [comment]
Screenshot the backend, not the frontend.

**Comment by gchodancar19** [comment]
![image](https://github.com/Jforjo/CSD/assets/132353162/dfb56c27-9138-45b1-af51-653a7e4a7e54)
![image](https://github.com/Jforjo/CSD/assets/132353162/594e69b2-d07b-476a-83ee-18034533062c)
![image](https://github.com/Jforjo/CSD/assets/132353162/c362d524-f19d-4421-ab60-c04446098730)

**Comment by Jforjo** [comment]
So what's the error you're getting?

**Comment by gchodancar19** [comment]
So after logging in it use to straight away take me to dashboard.php but now it's not and for signup page it's not creating anything in databases but on Monday I created several users.

**Comment by Jforjo** [comment]
In your createuser.php you have `isset($_POST['firstname']` but it should have 'firstName' with the capital 'N'. Same with 'lastname', it needs to be 'lastName'

**Comment by Jforjo** [comment]
You just need to make sure they are the same.
![image](https://github.com/Jforjo/CSD/assets/58900155/f0ebd9ca-5f4a-4d4a-8242-6c7ac6fc4b13)
![image](https://github.com/Jforjo/CSD/assets/58900155/14ffe178-2232-491a-89f8-82de23a22f49)

**Comment by Jforjo** [comment]
Also, when logging in you MUST include a lowercase letter, an uppercase letter, a number, and a special character. Otherwise, it wont work

**Comment by gchodancar19** [comment]
It is for the password I need to include all those things.

**Comment by gchodancar19** [comment]
![image](https://github.com/Jforjo/CSD/assets/132353162/9c0323ba-4564-4627-ace8-21153667b3f5)
I tried that but it's giving me this.

**Comment by Jforjo** [comment]
Did you change these? https://github.com/Jforjo/CSD/issues/32#issuecomment-2022853090

**Comment by Jforjo** [comment]
* Change "firstname" to "firstName"
* "lastname" to "lastName"
* Enter a password that follows the password policy

If it still doesn't work then just commit it and make a pull request.

**Comment by gchodancar19** [comment]
I have done that but still it's not working.

**Comment by Jforjo** [comment]
Solution: Moving some brackets so the strlen function only contains the variable without the '>' symbol, as that turned it to a bool, which is an invalid parameter type for the strlen function. see before and after below
```php
// Before
if (strlen($_POST['firstname'] < 8)) {
```
```php
// After
if (strlen($_POST['firstname']) < 8) {
```
