### ISSUE TITLE
JH - Button value not passing to PHP

### ISSUE THREAD

**Issue by Jforjo** [Jforjo/CSD#8]
## Description
When admin attempts to accept or deny a user on the dashboard (see 1<sup>st</sup> screenshot), __all__ the information in the form should be submitted. However, the values of the submit buttons do not get submitted, even though they name both `name` and `value` attributes.
## To Reproduce
1. Log in with a lecturer or admin account.
2. Make sure there is a newly created user who is still pending approval.
3. Enter student number for the user, if a lecturer is logged in; otherwise, leave this field blank to make the user a lecturer.
4. Click accept.
5. A dialog should appear saying "Invalid POST action" (see 2<sup>nd</sup> screenshot).
## Expected behaviour
A dialog should appear saying that the user has been successfully accepted.
## Screenshots
![Screenshot of form to accept user](https://github.com/Jforjo/CSD/assets/58900155/0f800d08-210f-411c-855d-115762df3199)
![Screenshot of the error dialog that appears when clicking either the 'accept' or 'deny' button](https://github.com/Jforjo/CSD/assets/58900155/b92f98f3-9216-423e-9d0b-d19ae98cab4b)
![Screenshot of PHP code that checks if `isset` of the POST 'action'](https://github.com/Jforjo/CSD/assets/58900155/39971e67-e3da-40c8-8fe4-52336335075d)
## Code location
* Branch: https://github.com/Jforjo/CSD/tree/JH-Admin-Management
* Commit: d435d7e
* File: /pages/admin/dashboard.php
## Additional Information
* Date/Time of issue: 05/03/2024 12:52
* The error that is returned is a custom made error message within the PHP file '/php/acceptstudent.php' (see 3<sup>rd</sup> screenshot).

**Comment by chrisn02** [comment]
I've not tested this so can't say for certain, but could this be a cause of the error? in acceptstudent.php it checks to see if 'state' = accept, but it might need to check for 'action' = accept instead

https://github.com/Jforjo/CSD/blob/c757830e64dcb2ed935a26ee635b5f1dc05e3edf/php/acceptstudent.php#L91-L94

**Comment by Jforjo** [comment]
Thanks for pointing that out. However, if you look at the line numbers, the check that throws the error happens a lot earlier, so although what you've pointed out is an error, it's unrelated to the error in this issue.

**Comment by Jforjo** [comment]
Fixed by manually appending the value onto the FormData. Although this shouldn't be needed, it is.
```javascript
formData.append(e.submitter.name, e.submitter.value);
```
